# Generated by Django 5.1.4 on 2025-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employerprofile_delete_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='first_name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='last_name',
            field=models.CharField(default='Default Last Name', max_length=255),
        ),
    ]
